"""Add Parent

Revision ID: 88068f7d69de
Revises: c91fe899ced1
Create Date: 2026-03-30 11:45:42.045267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88068f7d69de'
down_revision: Union[str, Sequence[str], None] = 'c91fe899ced1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_chunk_type'), table_name='chunks')
    op.drop_index(op.f('ix_parent_chunk_id'), table_name='chunks')
    op.drop_constraint(op.f('chunks_parent_chunk_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'chunks', ['parent_id'], ['chunk_id'])
    op.drop_column('chunks', 'chunk_type')
    op.drop_column('chunks', 'parent_chunk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('parent_chunk_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chunks', sa.Column('chunk_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_parent_chunk_id_fkey'), 'chunks', 'chunks', ['parent_chunk_id'], ['chunk_id'])
    op.create_index(op.f('ix_parent_chunk_id'), 'chunks', ['parent_chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_type'), 'chunks', ['chunk_type'], unique=False)
    op.drop_column('chunks', 'parent_id')
    # ### end Alembic commands ###
