"""add_parent_child_chunking

Revision ID: c91fe899ced1
Revises: f78b2533a4e3
Create Date: 2026-03-29 10:03:47.635248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91fe899ced1'
down_revision: Union[str, Sequence[str], None] = 'f78b2533a4e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('parent_chunk_id', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('chunk_type', sa.String(), nullable=True))
    op.create_index('ix_chunk_type', 'chunks', ['chunk_type'], unique=False)
    op.create_index('ix_parent_chunk_id', 'chunks', ['parent_chunk_id'], unique=False)
    op.create_foreign_key(None, 'chunks', 'chunks', ['parent_chunk_id'], ['chunk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_index('ix_parent_chunk_id', table_name='chunks')
    op.drop_index('ix_chunk_type', table_name='chunks')
    op.drop_column('chunks', 'chunk_type')
    op.drop_column('chunks', 'parent_chunk_id')
    # ### end Alembic commands ###
