services:
    mongodb:
        #from mogotags choose any one
        image: mongo:latest
        
        container_name: mongodb
        
        ports:
        # this is the default port 27017, move to another port 27007
            - "27007:27017"
        volumes:
        # where to write the data
            - "./mongodb:/data/db"
        networks:
            - backend
        # if it fails, then restart
        restart: always

    pgvector:
        image: pgvector/pgvector:pg17-trixie
        container_name: pgvector
        ports:
        - "5432:5432"
        volumes:
        - pgvector_data:/var/lib/postgresql/data
        environment:
        - POSTGRES_PASSWORD=300922
        networks:
        - backend
        restart: always
        # healthcheck:
        # test: ["CMD-SHELL", "pg_isready -U postgres"]
        # interval: 5s
        # timeout: 5s
        # retries: 5
        # start_period: 10s

networks:
    backend:

volumes:
    pgvector_data:
        